// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: gvknTxV5jyRUgarcF2VvaJ
// Component: eXSsJQPKVW
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: gvknTxV5jyRUgarcF2VvaJ/projectcss
import * as sty from "./PlasmicHomepage.module.css"; // plasmic-import: eXSsJQPKVW/css
import Vector7Icon from "./icons/PlasmicIcon__Vector7"; // plasmic-import: Mw6igkfHr7/icon
import ЛоготипIcon from "./icons/PlasmicIcon__\u041B\u043E\u0433\u043E\u0442\u0438\u043F"; // plasmic-import: MQoPmcN5kM/icon
import LoginIcoIcon from "./icons/PlasmicIcon__LoginIco"; // plasmic-import: HDCmHHaetZ/icon
import IconfinderHandCursor26398271Icon from "./icons/PlasmicIcon__IconfinderHandCursor26398271"; // plasmic-import: SLrOvs1PyD/icon

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

function PlasmicHomepage__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <React.Fragment>
      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"доброПожаловать"}
            data-plasmic-override={overrides.доброПожаловать}
            className={classNames(defaultcss.all, sty.добропожаловать)}
          >
            {false ? (
              <div
                data-plasmic-name={"group223"}
                data-plasmic-override={overrides.group223}
                className={classNames(defaultcss.all, sty.group223)}
              >
                <div
                  data-plasmic-name={"rectangle461"}
                  data-plasmic-override={overrides.rectangle461}
                  className={classNames(defaultcss.all, sty.rectangle461)}
                />

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.text__xJLw
                  )}
                >
                  {"Вернуться к другим Инициативам"}
                </div>

                <div
                  data-plasmic-name={"iconsArrowLeft24Px"}
                  data-plasmic-override={overrides.iconsArrowLeft24Px}
                  className={classNames(defaultcss.all, sty.iconsArrowLeft24Px)}
                >
                  <div
                    data-plasmic-name={"rectangle470"}
                    data-plasmic-override={overrides.rectangle470}
                    className={classNames(defaultcss.all, sty.rectangle470)}
                  />

                  <Vector7Icon
                    className={classNames(defaultcss.all, sty.svg__uapWd)}
                    role={"img"}
                  />
                </div>
              </div>
            ) : null}

            <div
              data-plasmic-name={"widgetsHeaderInner"}
              data-plasmic-override={overrides.widgetsHeaderInner}
              className={classNames(defaultcss.all, sty.widgetsHeaderInner)}
            >
              <ЛоготипIcon
                className={classNames(defaultcss.all, sty.svg__w9FT0)}
                role={"img"}
              />

              <div
                data-plasmic-name={"logInSignIn"}
                data-plasmic-override={overrides.logInSignIn}
                className={classNames(defaultcss.all, sty.logInSignIn)}
              >
                <LoginIcoIcon
                  className={classNames(defaultcss.all, sty.svg__xiEu)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.text___1Wen6
                  )}
                >
                  {"konstantin@konstantinopolsky.com   Выйти"}
                </div>

                {false ? (
                  <div
                    data-plasmic-name={"rectangle487"}
                    data-plasmic-override={overrides.rectangle487}
                    className={classNames(defaultcss.all, sty.rectangle487)}
                  />
                ) : null}
                {false ? (
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__v1FM5
                    )}
                  >
                    {"Зарегистрироваться"}
                  </div>
                ) : null}
              </div>
            </div>

            <div
              data-plasmic-name={"rectangle533"}
              data-plasmic-override={overrides.rectangle533}
              className={classNames(defaultcss.all, sty.rectangle533)}
            />

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.text__mJYd3
              )}
            >
              {"Мои заявки"}
            </div>

            <div
              data-plasmic-name={"group268"}
              data-plasmic-override={overrides.group268}
              className={classNames(defaultcss.all, sty.group268)}
            >
              <div
                data-plasmic-name={"group267"}
                data-plasmic-override={overrides.group267}
                className={classNames(defaultcss.all, sty.group267)}
              >
                <div
                  data-plasmic-name={"rectangle28"}
                  data-plasmic-override={overrides.rectangle28}
                  className={classNames(defaultcss.all, sty.rectangle28)}
                >
                  <div
                    data-plasmic-name={
                      "этиДетиМоглиБыИдтиПервогоСентябряВШколуСБукетомОсеннихАстрГордоДержаОтцаЗаРукуНоЭтогоНеПроизойдетУКогоТоПапаАУКогоТоМамаВотУжеМногоМесяцевВЗаключении"
                    }
                    data-plasmic-override={
                      overrides.этиДетиМоглиБыИдтиПервогоСентябряВШколуСБукетомОсеннихАстрГордоДержаОтцаЗаРукуНоЭтогоНеПроизойдетУКогоТоПапаАУКогоТоМамаВотУжеМногоМесяцевВЗаключении
                    }
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.этидетимоглибыидтипервогосентябрявшколусбукетомосеннихастргордодержаотцазарукуноэтогонепроизойдетукоготопапааукоготомамавотужемногомесяцеввзаключении
                    )}
                  >
                    {
                      "Эти дети могли бы идти первого сентября в школу с букетом осенних астр, гордо держа отца за руку, но этого не произойдет. У кого-то папа, а у кого-то мама вот уже много месяцев в заключении. "
                    }
                  </div>
                </div>

                <p.Stack
                  as={"div"}
                  data-plasmic-name={"frame58"}
                  data-plasmic-override={overrides.frame58}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.frame58)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text__bRo8
                    )}
                  >
                    {"Детали"}
                  </div>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  data-plasmic-name={"frame59"}
                  data-plasmic-override={overrides.frame59}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.frame59)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.text___4IkA
                    )}
                  >
                    {"Поделиться"}
                  </div>
                </p.Stack>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.text__cct6W
                  )}
                >
                  {
                    "Помощь девушке, которая попала в ДТП при экстренной релокации"
                  }
                </div>

                <div
                  data-plasmic-name={"maskGroup"}
                  data-plasmic-override={overrides.maskGroup}
                  className={classNames(defaultcss.all, sty.maskGroup)}
                >
                  <div
                    data-plasmic-name={"снимокЭкрана20210823В11191"}
                    data-plasmic-override={overrides.снимокЭкрана20210823В11191}
                    className={classNames(
                      defaultcss.all,
                      sty.снимокэкрана20210823В11191
                    )}
                  />
                </div>
              </div>

              <div
                data-plasmic-name={"mouseOver"}
                data-plasmic-override={overrides.mouseOver}
                className={classNames(defaultcss.all, sty.mouseOver)}
              >
                {false ? (
                  <IconfinderHandCursor26398271Icon
                    className={classNames(defaultcss.all, sty.svg__fcvT)}
                    role={"img"}
                  />
                ) : null}
              </div>
            </div>

            <p.Stack
              as={"div"}
              data-plasmic-name={"frame60"}
              data-plasmic-override={overrides.frame60}
              hasGap={true}
              className={classNames(defaultcss.all, sty.frame60)}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.text__jKMiI
                )}
              >
                {"Создать заявку"}
              </div>
            </p.Stack>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "доброПожаловать",
    "group223",
    "rectangle461",
    "iconsArrowLeft24Px",
    "rectangle470",
    "widgetsHeaderInner",
    "logInSignIn",
    "rectangle487",
    "rectangle533",
    "group268",
    "group267",
    "rectangle28",
    "этиДетиМоглиБыИдтиПервогоСентябряВШколуСБукетомОсеннихАстрГордоДержаОтцаЗаРукуНоЭтогоНеПроизойдетУКогоТоПапаАУКогоТоМамаВотУжеМногоМесяцевВЗаключении",
    "frame58",
    "frame59",
    "maskGroup",
    "снимокЭкрана20210823В11191",
    "mouseOver",
    "frame60"
  ],

  доброПожаловать: [
    "доброПожаловать",
    "group223",
    "rectangle461",
    "iconsArrowLeft24Px",
    "rectangle470",
    "widgetsHeaderInner",
    "logInSignIn",
    "rectangle487",
    "rectangle533",
    "group268",
    "group267",
    "rectangle28",
    "этиДетиМоглиБыИдтиПервогоСентябряВШколуСБукетомОсеннихАстрГордоДержаОтцаЗаРукуНоЭтогоНеПроизойдетУКогоТоПапаАУКогоТоМамаВотУжеМногоМесяцевВЗаключении",
    "frame58",
    "frame59",
    "maskGroup",
    "снимокЭкрана20210823В11191",
    "mouseOver",
    "frame60"
  ],

  group223: ["group223", "rectangle461", "iconsArrowLeft24Px", "rectangle470"],
  rectangle461: ["rectangle461"],
  iconsArrowLeft24Px: ["iconsArrowLeft24Px", "rectangle470"],
  rectangle470: ["rectangle470"],
  widgetsHeaderInner: ["widgetsHeaderInner", "logInSignIn", "rectangle487"],
  logInSignIn: ["logInSignIn", "rectangle487"],
  rectangle487: ["rectangle487"],
  rectangle533: ["rectangle533"],
  group268: [
    "group268",
    "group267",
    "rectangle28",
    "этиДетиМоглиБыИдтиПервогоСентябряВШколуСБукетомОсеннихАстрГордоДержаОтцаЗаРукуНоЭтогоНеПроизойдетУКогоТоПапаАУКогоТоМамаВотУжеМногоМесяцевВЗаключении",
    "frame58",
    "frame59",
    "maskGroup",
    "снимокЭкрана20210823В11191",
    "mouseOver"
  ],

  group267: [
    "group267",
    "rectangle28",
    "этиДетиМоглиБыИдтиПервогоСентябряВШколуСБукетомОсеннихАстрГордоДержаОтцаЗаРукуНоЭтогоНеПроизойдетУКогоТоПапаАУКогоТоМамаВотУжеМногоМесяцевВЗаключении",
    "frame58",
    "frame59",
    "maskGroup",
    "снимокЭкрана20210823В11191"
  ],

  rectangle28: [
    "rectangle28",
    "этиДетиМоглиБыИдтиПервогоСентябряВШколуСБукетомОсеннихАстрГордоДержаОтцаЗаРукуНоЭтогоНеПроизойдетУКогоТоПапаАУКогоТоМамаВотУжеМногоМесяцевВЗаключении"
  ],

  этиДетиМоглиБыИдтиПервогоСентябряВШколуСБукетомОсеннихАстрГордоДержаОтцаЗаРукуНоЭтогоНеПроизойдетУКогоТоПапаАУКогоТоМамаВотУжеМногоМесяцевВЗаключении:
    [
      "этиДетиМоглиБыИдтиПервогоСентябряВШколуСБукетомОсеннихАстрГордоДержаОтцаЗаРукуНоЭтогоНеПроизойдетУКогоТоПапаАУКогоТоМамаВотУжеМногоМесяцевВЗаключении"
    ],

  frame58: ["frame58"],
  frame59: ["frame59"],
  maskGroup: ["maskGroup", "снимокЭкрана20210823В11191"],
  снимокЭкрана20210823В11191: ["снимокЭкрана20210823В11191"],
  mouseOver: ["mouseOver"],
  frame60: ["frame60"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHomepage__ArgProps,
      internalVariantPropNames: PlasmicHomepage__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    доброПожаловать: makeNodeComponent("доброПожаловать"),
    group223: makeNodeComponent("group223"),
    rectangle461: makeNodeComponent("rectangle461"),
    iconsArrowLeft24Px: makeNodeComponent("iconsArrowLeft24Px"),
    rectangle470: makeNodeComponent("rectangle470"),
    widgetsHeaderInner: makeNodeComponent("widgetsHeaderInner"),
    logInSignIn: makeNodeComponent("logInSignIn"),
    rectangle487: makeNodeComponent("rectangle487"),
    rectangle533: makeNodeComponent("rectangle533"),
    group268: makeNodeComponent("group268"),
    group267: makeNodeComponent("group267"),
    rectangle28: makeNodeComponent("rectangle28"),
    этиДетиМоглиБыИдтиПервогоСентябряВШколуСБукетомОсеннихАстрГордоДержаОтцаЗаРукуНоЭтогоНеПроизойдетУКогоТоПапаАУКогоТоМамаВотУжеМногоМесяцевВЗаключении:
      makeNodeComponent(
        "этиДетиМоглиБыИдтиПервогоСентябряВШколуСБукетомОсеннихАстрГордоДержаОтцаЗаРукуНоЭтогоНеПроизойдетУКогоТоПапаАУКогоТоМамаВотУжеМногоМесяцевВЗаключении"
      ),

    frame58: makeNodeComponent("frame58"),
    frame59: makeNodeComponent("frame59"),
    maskGroup: makeNodeComponent("maskGroup"),
    снимокЭкрана20210823В11191: makeNodeComponent("снимокЭкрана20210823В11191"),
    mouseOver: makeNodeComponent("mouseOver"),
    frame60: makeNodeComponent("frame60"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
